INSERT INTO [dbo].[City]
    (CountryID, City) VALUES
    	(1, 'New York City'), 
	(1, 'Los Angeles'), 
	(1, 'Chicago'), 
	(1, 'Houston'), 
	(1, 'Phoenix'), 
	(1, 'Philadelphia'), 
	(1, 'San Antonio'), 
	(1, 'San Diego'), 
	(1, 'Dallas'), 
	(1, 'San Jose'), 
	(2, 'Toronto'), 
	(2, 'Montreal'), 
	(2, 'Vancouver'), 
	(2, 'Ottawa'), 
	(2, 'Calgary'), 
	(2, 'Edmonton'), 
	(2, 'Quebec City'), 
	(2, 'Winnipeg'), 
	(2, 'Hamilton'), 
	(2, 'Kitchener'), 
	(3, 'London'), 
	(3, 'Birmingham'), 
	(3, 'Manchester'), 
	(3, 'Leeds'), 
	(3, 'Glasgow'), 
	(3, 'Newcastle upon Tyne'), 
	(3, 'Liverpool'), 
	(3, 'Sheffield'), 
	(3, 'Bristol'), 
	(3, 'Nottingham'), 
	(4, 'Paris'), 
	(4, 'Marseille'), 
	(4, 'Lyon'), 
	(4, 'Toulouse'), 
	(4, 'Nice'), 
	(4, 'Nantes'), 
	(4, 'Strasbourg'), 
	(4, 'Montpellier'), 
	(4, 'Bordeaux'), 
	(4, 'Lille'), 
	(5, 'Berlin'), 
	(5, 'Hamburg'), 
	(5, 'Munich'), 
	(5, 'Cologne'), 
	(5, 'Frankfurt'), 
	(5, 'Stuttgart'), 
	(5, 'Dusseldorf'), 
	(5, 'Dortmund'), 
	(5, 'Essen'), 
	(5, 'Leipzig'), 
	(6, 'Rome'), 
	(6, 'Milan'), 
	(6, 'Naples'), 
	(6, 'Turin'), 
	(6, 'Palermo'), 
	(6, 'Genoa'), 
	(6, 'Bologna'), 
	(6, 'Florence'), 
	(6, 'Venice'), 
	(6, 'Verona'), 
	(7, 'Madrid'), 
	(7, 'Barcelona'), 
	(7, 'Valencia'), 
	(7, 'Seville'), 
	(7, 'Zaragoza'), 
	(7, 'Malaga'), 
	(7, 'Murcia'), 
	(7, 'Palma'), 
	(7, 'LasPalmas de Gran Canaria'), 
	(7, 'Bilbao'), 
	(8, 'Sydney'), 
	(8, 'Melbourne'), 
	(8, 'Brisbane'), 
	(8, 'Perth'), 
	(8, 'Adelaide'), 
	(8, 'GoldCoast'), 
	(8, 'Canberra'), 
	(8, 'Newcastle'), 
	(8, 'Wollongong'), 
	(8, 'Geelong'), 
	(9, 'Tokyo'), 
	(9, 'Yokohama'), 
	(9, 'Osaka'), 
	(9, 'Nagoya'), 
	(9, 'Sapporo'), 
	(9, 'Kobe'), 
	(9, 'Kyoto'), 
	(9, 'Fukuoka'), 
	(9, 'Kawasaki'), 
	(9, 'Hiroshima'), 
	(10, 'Beijing'), 
	(10, 'Shanghai'), 
	(10, 'Guangzhou'), 
	(10, 'Shenzhen'), 
	(10, 'Tianjin'), 
	(10, 'Wuhan'), 
	(10, 'Dongguan'), 
	(10, 'Chengdu'), 
	(10, 'Chongqing'), 
	(10, 'Nanjing'), 
	(11, 'SãoPaulo'), 
	(11, 'RiodeJaneiro'), 
	(11, 'Brasília'), 
	(11, 'Salvador'), 
	(11, 'Fortaleza'), 
	(11, 'BeloHorizonte'), 
	(11, 'Manaus'), 
	(11, 'Curitiba'), 
	(11, 'Recife'), 
	(11, 'Porto Alegre'), 
	(12, 'MexicoCity'), 
	(12, 'Ecatepec'), 
	(12, 'Guadalajara'), 
	(12, 'Puebla'), 
	(12, 'Juárez'), 
	(12, 'Tijuana'), 
	(12, 'León'), 
	(12, 'Monterrey'), 
	(12, 'Zapopan'), 
	(12, 'Nezahualcóyotl'), 
	(13, 'Buenos Aires'), 
	(13, 'Córdoba'), 
	(13, 'Rosario'), 
	(13, 'La Plata'), 
	(13, 'Mar del Plata'), 
	(13, 'San Miguel de Tucumán'), 
	(13, 'Salta'), 
	(13, 'Santa Fe'), 
	(13, 'Corrientes'), 
	(13, 'Bahía Blanca'), 
	(14, 'Johannesburg'), 
	(14, 'Cape Town'), 
	(14, 'Durban'), 
	(14, 'Pretoria'), 
	(14, 'Port Elizabeth'), 
	(14, 'Bloemfontein'), 
	(14, 'East London'), 
	(14, 'Nelspruit'), 
	(14, 'Kimberley'), 
	(14, 'Polokwane'), 
	(15, 'Lagos'), 
	(15, 'Kano'), 
	(15, 'Ibadan'), 
	(15, 'Abuja'), 
	(15, 'Port Harcourt'), 
	(15, 'Benin City'), 
	(15, 'Maiduguri'), 
	(15, 'Zaria'), 
	(15, 'Aba'), 
	(15, 'Jos'), 
	(16, 'Moscow'), 
	(16, 'Saint Petersburg'), 
	(16, 'Novosibirsk'), 
	(16, 'Yekaterinburg'), 
	(16, 'Nizhny Novgorod'), 
	(16, 'Samara'), 
	(16, 'Omsk'), 
	(16, 'Kazan'), 
	(16, 'Rostov-on-Don'), 
	(16, 'Chelyabinsk'), 
	(17, 'Mumbai'), 
	(17, 'Delhi'), 
	(17, 'Bangalore'), 
	(17, 'Kolkata'), 
	(17, 'Chennai'), 
	(17, 'Hyderabad'), 
	(17, 'Pune'), 
	(17, 'Ahmedabad'), 
	(17, 'Surat'), 
	(17, 'Jaipur'), 
	(18, 'Karachi'), 
	(18, 'Lahore'), 
	(18, 'Faisalabad'), 
	(18, 'Rawalpindi'), 
	(18, 'Multan'), 
	(18, 'Hyderabad'), 
	(18, 'Gujranwala'), 
	(18, 'Peshawar'), 
	(18, 'Abbottabad'), 
	(18, 'Quetta'), 
	(19, 'Istanbul'), 
	(19, 'Ankara'), 
	(19, 'Izmir'), 
	(19, 'Bursa'), 
	(19, 'Adana'), 
	(19, 'Gaziantep'), 
	(19, 'Konya'), 
	(19, 'Antalya'), 
	(19, 'Kayseri'), 
	(19, 'Mersin'), 
	(20, 'Cairo'), 
	(20, 'Alexandria'), 
	(20, 'Giza'), 
	(20, 'Shubra El-Kheima'), 
	(20, 'Port Said'), 
	(20, 'Suez'), 
	(20, 'Luxor'), 
	(20, 'Aswan'), 
	(20, 'Mansoura'), 
	(20, 'Tanta');

