INSERT INTO [SalesChannel] ([ChannelName], [CityID], [ContactDetails]) VALUES
	('Amazon', 150, 'contact@amazon.com'),
	('eBay', 163, 'contact@ebay.com'),
	('Walmart', 188, 'contact@walmart.com'),
	('Alibaba', 45, 'contact@alibaba.com'),
	('Etsy', 44, 'contact@etsy.com'),
	('Target', 199, 'contact@target.com'),
	('Best Buy', 44, 'contact@bestbuy.com'),
	('Costco', 133, 'contact@costco.com'),
	('Home Depot', 132, 'contact@homedepot.com'),
	('Lowes', 182, 'contact@lowes.com'),
	('Macys', 63, 'contact@macys.com'),
	('Nordstrom', 21, 'contact@nordstrom.com'),
	('Gap', 53, 'contact@gap.com'),
	('Nike', 186, 'contact@nike.com'),
	('Adidas', 10, 'contact@adidas.com'),
	('Zara', 85, 'contact@zara.com'),
	('H&M', 68, 'contact@hm.com'),
	('Forever 21', 35, 'contact@forever21.com'),
	('American Eagle Outfitters', 31, 'contact@ae.com'),
	('Sephora', 18, 'contact@sephora.com'),
	('Ulta Beauty', 14, 'contact@ultabeauty.com'),
	('CVS', 99, 'contact@cvs.com'),
	('Walgreens', 134, 'contact@walgreens.com'),
	('Starbucks', 51, 'contact@starbucks.com'),
	('Dunkin', 107, 'contact@dunkin.com'),
	('McDonalds', 2, 'contact@mcdonalds.com'),
	('Burger King', 105, 'contact@burgerking.com'),
	('Subway', 144, 'contact@subway.com'),
	('Dominos Pizza', 197, 'contact@dominos.com'),
	('Pizza Hut', 200, 'contact@pizzahut.com');
