INSERT INTO [Product] ([Description], [Category], [UnitPrice]) VALUES
	('HomeMind - Smart Home Hub and Voice Assistant', 'Smart Home Devices', 3640.0),
	('PrintMate - Custom Photo Phone Cases', 'Personalized/Customized Gifts', 2165.0),
	('GlowGenius - Brightening Facial Mask', 'Skincare and Beauty Products', 2595.0),
	('SoundHive - True Wireless Earbuds', 'Wireless Earbuds and Headphones', 1447.0),
	('JuiceBox - Ultra-Compact Power Bank', 'Portable Power Banks and Chargers', 8505.0),
	('EarthEra - Reusable Grocery Bags', 'Sustainable and Eco-Friendly Products', 13041.0),
	('GameMaster - Wireless Gaming Controller', 'Gaming Accessories', 6289.0),
	('PhoneArmor - Shockproof Phone Case', 'Smartphone Cases and Accessories', 1602.0),
	('FlexCore - Non-Slip Yoga Mat', 'Yoga Mats, Fitness Equipment, and Workout Clothes', 10241.0),
	('WatchDog - HD Smart Security Camera', 'Home Security Cameras and Doorbells', 8957.0),
	('FunZone - Indoor/Outdoor Play Tent', 'Childrens Toys and Games', 5584.0),
	('SoundBox - Portable Bluetooth Speaker', 'Bluetooth Speakers and Soundbars', 3629.0),
	('PetHaven - Orthopedic Pet Bed', 'Pet Products', 5594.0),
	('ArtisanLane - Decorative Throw Pillows', 'Home Decor and Accessories', 7443.0),
	('LeafLife - Reusable Bamboo Water Bottle}', 'Sustainable and Eco-Friendly Products', 17497.0),
	('PhoneArmor - Shockproof Phone Case', 'Smartphone Cases and Accessories', 13457.0),
	('FitTracker - Advanced Fitness Tracker', 'Smartwatches and Fitness Trackers', 1858.0),
	('CustomCraze - Personalized Coffee Mugs', 'Personalized/Customized Gifts', 10440.0),
	('SkinZen - Hydrating Facial Moisturizer', 'Skincare and Beauty Products', 16290.0),
	('AirBuds - True Wireless Earbuds', 'Wireless Earbuds and Headphones', 1198.0),
	('ChargeMate - Ultra-Fast Charging Power Bank', 'Portable Power Banks and Chargers', 9619.0),
	('EcoBloom - Biodegradable Flower Pots', 'Sustainable and Eco-Friendly Products', 16069.0),
	('PlayPulse - Gaming Headset with LED Lights', 'Gaming Accessories', 18903.0),
	('ToughShield - Rugged Phone Case', 'Smartphone Cases and Accessories', 4300.0),
	('YogaFlex - Stretchable Yoga Pants', 'Yoga Mats, Fitness Equipment, and Workout Clothes', 11286.0),
	('HomeWatch - HD Smart Doorbell', 'Home Security Cameras and Doorbells', 6934.0),
	('FunFiesta - Party Pinata Game', 'Childrens Toys and Games', 18891.0),
	('BoomBar - Wireless Soundbar with Subwoofer', 'Bluetooth Speakers and Soundbars', 4675.0),
	('FurBall - Self-Cleaning Cat Litter Box', 'Pet Products', 13483.0),
	('DecoHaus - Minimalist Wall Clock', 'Home Decor and Accessories', 4621.0),
	('EcoStraw - Reusable Stainless Steel Straw Set', 'Sustainable and Eco-Friendly Products', 2983.0),
	('SmartLife - Voice-Activated Smart Home System', 'Smart Home Devices', 2969.0),
	('NameFrame - Personalized Picture Frame', 'Personalized/Customized Gifts', 9997.0),
	('ClearSkin - Acne Treatment Cream', 'Skincare and Beauty Products', 8054.0),
	('SonicFlow - Noise-Canceling Headphones', 'Wireless Earbuds and Headphones', 5132.0),
	('PowerPal - High-Capacity Power Bank', 'Portable Power Banks and Chargers', 10649.0),
	('EarthyEats - Reusable Beeswax Food Wraps', 'Sustainable and Eco-Friendly Products', 2986.0),
	('GamingGrip - Ergonomic Gaming Mousepad', 'Gaming Accessories', 86.0),
	('SlimShield - Ultra-Thin Phone Case', 'Smartphone Cases and Accessories', 1128.0),
	('FitFlow - Anti-Slip Yoga Mat', 'Yoga Mats, Fitness Equipment, and Workout Clothes', 2584.0),
	('DoorDefender - Wireless Door Sensor Alarm', 'Home Security Cameras and Doorbells', 3657.0),
	('PlayLand - Indoor/Outdoor Play Tent', 'Childrens Toys and Games', 17341.0),
	('SoundWave - Waterproof Bluetooth Speaker', 'Bluetooth Speakers and Soundbars', 15787.0),
	('Pawsome - Portable Pet Water Bottle', 'Pet Products', 389.0),
	('LuxeLounge - Velvet Decorative Pillows', 'Home Decor and Accessories', 1414.0),
	('EcoFuel - Reusable Bamboo Utensil Set', 'Sustainable and Eco-Friendly Products', 15044.0),
	('FitTracker - Advanced Fitness Tracker', 'Smartwatches and Fitness Trackers', 1621.0),
	('CustomCraze - Personalized Coffee Mugs', 'Personalized/Customized Gifts', 6800.0),
	('SkinZen - Hydrating Facial Moisturizer', 'Skincare and Beauty Products', 5038.0),
	('AirBuds - True Wireless Earbuds', 'Wireless Earbuds and Headphones', 10223.0);
